import numpy as np

kernel = {
    'identity': np.array([[0, 0, 0],
                          [0, 1, 0],
                          [0, 0, 0]]),
    'edge detection': np.array([[1, 0, -1],
                                [0, 0, 0],
                                [-1, 0, 1]]),
    'laplacian': np.array([[0, -1, 0],
                           [-1, 4, -1],
                           [0, -1, 0]]),
    'laplacian w/ diagonals': np.array([[-1, -1, -1],
                                        [-1, 8, -1],
                                        [-1, -1, -1]]),
    'laplacian of gaussian': np.array([[0, 0, -1, 0, 0],
                                       [0, -1, -2, -1, 0],
                                       [-1, -2, 16, -2, -1],
                                       [0, -1, -2, -1, 0],
                                       [0, 0, -1, 0, 0]]),
    'scharr': np.array([[-3, 0, 3],
                        [-10, 0, 10],
                        [-3, 0, 3]]),
    'sobel edge horizontal': np.array([[-1, -2, -1],
                                       [0, 0, 0],
                                       [1, 2, 1]]),
    'sobel edge vertical': np.array([[-1, 0, 1],
                                     [-2, 0, 2],
                                     [-1, 0, 1]]),
    'line detection horizontal': np.array([[-1, -1, -1],
                                           [2, 2, 2],
                                           [-1, -1, -1]]),
    'line detection vertical': np.array([[-1, 2, -1],
                                         [-1, 2, -1],
                                         [-1, 2, -1]]),
    'line detection 45°': np.array([[-1, -1, 2],
                                     [-1, 2, -1],
                                     [2, -1, -1]]),
    'line detection 135°': np.array([[2, -1, -1],
                                      [-1, 2, -1],
                                      [-1, -1, 2]]),
    'box blur': (1/9)*np.ones((3, 3)),
    'gaussian blur 3x3': (1/16)*np.array([[1, 2, 1],
                                          [2, 4, 2],
                                          [1, 2, 1]]),
    'gaussian blur 5x5': (1/256)*np.array([[1, 4, 6, 4, 1],
                                           [4, 16, 24, 16, 4],
                                           [6, 24, 36, 24, 6],
                                           [4, 16, 24, 16, 4],
                                           [1, 4, 6, 4, 1]]),
    'sharpen': np.array([[0, -1, 0],
                         [-1, 5, -1],
                         [0, -1, 0]]),
    'unsharp masking': (-1/256)*np.array([[1, 4, 6, 4, 1],
                                          [4, 16, 24, 16, 4],
                                          [6, 24, -476, 24, 6],
                                          [4, 16, 24, 16, 4],
                                          [1, 4, 6, 4, 1]]),
}
